# compose.db.yaml → de infrastructuur:
# depend hier: wat start er eerst.., n te maken met de inhoud van de data al.
services:
  postgres:
    image: postgres:18-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - .env
    volumes:
      - db:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
